---
- name: Create/revert/remove LVM snapshot of node
  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    TERM: linux
  roles:
    - name: lvm_snapshots
      # lvm_snapshot_* vars provided via AAP2 job template and associated surveys
...
